credentials:
  usernames:
    komatsu:
      email: komatsu@ex.com
      name: komatsu
      password: $2b$12$QoAtFoOaKzjP9FZVWYJjPe6UNVmph0Nww0crBAxYE.FT3NFXko/N6
    miwacci:
      email: miwacci@example.com
      name: miwacci
      password: $2b$12$fXEnb/s81WHCRDZxbx1n1O88FZmztYrraEEPSrdZVp41Hq2wvZx1e
